AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
  DisplayCopNames: true

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*
Style/FrozenStringLiteralComment:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/TrailingEmptyLines:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: leading

Metrics/LineLength:
  Exclude:
    - spec/**/*
  Max: 100
Metrics/BlockLength:
  Exclude:
    - spec/**/*
